version: "2"

services:
  app:
    build: ./api
    volumes:
      - ./api:/go/src/go-poll/api
    working_dir: /go/src/go-poll/api
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - back-tier
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    ports: 
      - "6379:6379"
    networks:
      - back-tier
networks:
  back-tier: